// > console.log(process)
// process {
//   version: 'v16.13.2',
//   versions: {
//     node: '16.13.2',
//     v8: '9.4.146.24-node.14',
//     uv: '1.42.0',
//     zlib: '1.2.11',
//     brotli: '1.0.9',
//     ares: '1.18.1',
//     modules: '93',
//     nghttp2: '1.45.1',
//     napi: '8',
//     llhttp: '6.0.4',
//     openssl: '1.1.1l+quic',
//     cldr: '39.0',
//     icu: '69.1',
//     tz: '2021a',
//     unicode: '13.0',
//     ngtcp2: '0.1.0-DEV',
//     nghttp3: '0.1.0-DEV'
//   },
//   arch: 'x64',
//   platform: 'darwin',
//   release: {
//     name: 'node',
//     lts: 'Gallium',
//     sourceUrl: 'https://nodejs.org/download/release/v16.13.2/node-v16.13.2.tar.gz',
//     headersUrl: 'https://nodejs.org/download/release/v16.13.2/node-v16.13.2-headers.tar.gz'
//   },
//   _rawDebug: [Function: _rawDebug],
//   moduleLoadList: [
//     'Internal Binding native_module',
//     'Internal Binding errors',
//     'NativeModule internal/errors',
//     'Internal Binding config',
//     'Internal Binding constants',
//     'Internal Binding util',
//     'Internal Binding types',
//     'NativeModule internal/util',
//     'NativeModule internal/util/types',
//     'NativeModule internal/assert',
//     'NativeModule internal/validators',
//     'Internal Binding icu',
//     'NativeModule internal/util/inspect',
//     'NativeModule events',
//     'Internal Binding buffer',
//     'Internal Binding string_decoder',
//     'NativeModule internal/buffer',
//     'Internal Binding blob',
//     'NativeModule internal/encoding',
//     'Internal Binding symbols',
//     'Internal Binding messaging',
//     'NativeModule internal/worker/js_transferable',
//     'NativeModule internal/blob',
//     'NativeModule buffer',
//     'NativeModule internal/process/per_thread',
//     'Internal Binding process_methods',
//     'Internal Binding credentials',
//     'Internal Binding async_wrap',
//     'Internal Binding task_queue',
//     'NativeModule internal/async_hooks',
//     'NativeModule async_hooks',
//     'NativeModule internal/process/promises',
//     'NativeModule internal/fixed_queue',
//     'NativeModule internal/process/task_queues',
//     'Internal Binding trace_events',
//     'NativeModule internal/constants',
//     'NativeModule internal/console/constructor',
//     'NativeModule internal/console/global',
//     'NativeModule internal/util/inspector',
//     'Internal Binding inspector',
//     'NativeModule internal/querystring',
//     'NativeModule path',
//     'NativeModule querystring',
//     'Internal Binding url',
//     'NativeModule internal/url',
//     'NativeModule internal/util/debuglog',
//     'NativeModule util',
//     'Internal Binding performance',
//     'NativeModule internal/perf/utils',
//     'NativeModule internal/event_target',
//     'NativeModule internal/abort_controller',
//     'Internal Binding worker',
//     'NativeModule internal/streams/end-of-stream',
//     'NativeModule internal/streams/destroy',
//     'NativeModule internal/streams/legacy',
//     'NativeModule internal/streams/add-abort-signal',
//     'NativeModule internal/streams/buffer_list',
//     'NativeModule internal/streams/state',
//     'NativeModule string_decoder',
//     'NativeModule internal/streams/from',
//     'NativeModule internal/streams/readable',
//     'NativeModule internal/streams/writable',
//     'NativeModule internal/streams/duplex',
//     'NativeModule internal/streams/utils',
//     'NativeModule internal/streams/pipeline',
//     'NativeModule internal/streams/compose',
//     'NativeModule stream/promises',
//     'NativeModule internal/streams/transform',
//     'NativeModule internal/streams/passthrough',
//     'NativeModule stream',
//     'NativeModule internal/worker/io',
//     'Internal Binding timers',
//     'NativeModule internal/linkedlist',
//     'NativeModule internal/priority_queue',
//     'NativeModule internal/timers',
//     'NativeModule timers',
//     'NativeModule internal/perf/performance_entry',
//     'NativeModule internal/perf/observe',
//     'NativeModule internal/perf/nodetiming',
//     'NativeModule internal/perf/usertiming',
//     'NativeModule internal/perf/event_loop_utilization',
//     'NativeModule internal/histogram',
//     'NativeModule internal/perf/timerify',
//     'NativeModule internal/perf/performance',
//     'NativeModule internal/perf/event_loop_delay',
//     'NativeModule perf_hooks',
//     'NativeModule internal/process/execution',
//     'NativeModule internal/process/warning',
//     'Internal Binding fs',
//     'NativeModule internal/fs/utils',
//     'Internal Binding fs_dir',
//     'NativeModule internal/fs/dir',
//     'Internal Binding fs_event_wrap',
//     'Internal Binding uv',
//     'NativeModule internal/fs/watchers',
//     'NativeModule internal/fs/read_file_context',
//     'NativeModule fs',
//     'Internal Binding serdes',
//     'Internal Binding profiler',
//     'Internal Binding heap_utils',
//     ... 63 more items
//   ],
//   binding: [Function: binding],
//   _linkedBinding: [Function: _linkedBinding],
//   _events: [Object: null prototype] {
//     newListener: [ [Function: startListeningIfSignal], [Function (anonymous)] ],
//     removeListener: [ [Function: stopListeningIfSignal], [Function (anonymous)] ],
//     warning: [Function: onWarning],
//     SIGWINCH: [Function (anonymous)]
//   },
//   _eventsCount: 4,
//   _maxListeners: undefined,
//   domain: [Getter/Setter],
//   _exiting: false,
//   config: [Getter/Setter],
//   dlopen: [Function: dlopen],
//   uptime: [Function: uptime],
//   _getActiveRequests: [Function: _getActiveRequests],
//   _getActiveHandles: [Function: _getActiveHandles],
//   reallyExit: [Function: reallyExit],
//   _kill: [Function: _kill],
//   cpuUsage: [Function: cpuUsage],
//   resourceUsage: [Function: resourceUsage],
//   memoryUsage: [Function: memoryUsage] { rss: [Function: rss] },
//   kill: [Function: kill],
//   exit: [Function: exit],
//   openStdin: [Function (anonymous)],
//   getuid: [Function: getuid],
//   geteuid: [Function: geteuid],
//   getgid: [Function: getgid],
//   getegid: [Function: getegid],
//   getgroups: [Function: getgroups],
//   allowedNodeEnvironmentFlags: [Getter/Setter],
//   assert: [Function: deprecated],
//   features: {
//     inspector: true,
//     debug: false,
//     uv: true,
//     ipv6: true,
//     tls_alpn: true,
//     tls_sni: true,
//     tls_ocsp: true,
//     tls: true,
//     cached_builtins: [Getter]
//   },
//   _fatalException: [Function (anonymous)],
//   setUncaughtExceptionCaptureCallback: [Function (anonymous)],
//   hasUncaughtExceptionCaptureCallback: [Function: hasUncaughtExceptionCaptureCallback],
//   emitWarning: [Function: emitWarning],
//   nextTick: [Function: nextTick],
//   _tickCallback: [Function: runNextTicks],
//   _debugProcess: [Function: _debugProcess],
//   _debugEnd: [Function: _debugEnd],
//   _startProfilerIdleNotifier: [Function (anonymous)],
//   _stopProfilerIdleNotifier: [Function (anonymous)],
//   stdout: [Getter],
//   stdin: [Getter],
//   stderr: [Getter],
//   abort: [Function: abort],
//   umask: [Function: wrappedUmask],
//   chdir: [Function (anonymous)],
//   cwd: [Function: wrappedCwd],
//   initgroups: [Function: initgroups],
//   setgroups: [Function: setgroups],
//   setegid: [Function (anonymous)],
//   seteuid: [Function (anonymous)],
//   setgid: [Function (anonymous)],
//   setuid: [Function (anonymous)],
//   env: {
//     USER: 'austin',
//     __CFBundleIdentifier: 'com.microsoft.VSCode',
//     COMMAND_MODE: 'unix2003',
//     LOGNAME: 'austin',
//     PATH: '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin',
//     SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.n9EmENjLPy/Listeners',
//     SHELL: '/bin/bash',
//     HOME: '/Users/austin',
//     __CF_USER_TEXT_ENCODING: '0x1F6:0x0:0x0',
//     TMPDIR: '/var/folders/l1/xfkvj5653zsbhxxl3sf5ptfh0000gp/T/',
//     XPC_SERVICE_NAME: '0',
//     XPC_FLAGS: '0x0',
//     ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
//     APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL: 'true',
//     PWD: '/Users/austin/Desktop/devmoutain/specs-exercise/web-node-drills-1/app-2',
//     LANG: 'en_US.UTF-8',
//     TERM: 'xterm-256color',
//     SHLVL: '3',
//     TERM_PROGRAM_VERSION: '1.65.2',
//     TERM_SESSION_ID: '09B4B54E-4969-4863-962F-C246EE7DC211',
//     TERM_PROGRAM: 'vscode',
//     COLORTERM: 'truecolor',
//     VSCODE_GIT_IPC_HANDLE: '/var/folders/l1/xfkvj5653zsbhxxl3sf5ptfh0000gp/T/vscode-git-cb6b953863.sock',
//     GIT_ASKPASS: '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh',
//     VSCODE_GIT_ASKPASS_NODE: '/Applications/Visual Studio Code.app/Contents/MacOS/Electron',
//     VSCODE_GIT_ASKPASS_EXTRA_ARGS: '--ms-enable-electron-run-as-node',
//     VSCODE_GIT_ASKPASS_MAIN: '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js',
//     OLDPWD: '/Users/austin/Desktop/devmoutain/specs-exercise/web-node-drills-1',
//     _: '/usr/local/bin/node'
//   },
//   title: 'node',
//   argv: [ '/usr/local/bin/node' ],
//   execArgv: [],
//   pid: 5057,
//   ppid: 4453,
//   execPath: '/usr/local/bin/node',
//   debugPort: 9229,
//   hrtime: [Function: hrtime] { bigint: [Function: hrtimeBigInt] },
//   argv0: 'node',
//   _preload_modules: [],
//   setSourceMapsEnabled: [Function: setSourceMapsEnabled],
//   [Symbol(kCapture)]: false
// }
// undefined
// > 